List<String> kidneyCareTips = [
  "Stay hydrated for kidney health.",
  "Monitor blood pressure regularly.",
  "Limit salt intake for kidneys.",
  "Eat a balanced diet consistently.",
  "Exercise regularly for kidney health.",
  "Avoid smoking for kidney care.",
  "Control blood sugar levels effectively.",
  "Manage stress for kidney wellness.",
  "Limit alcohol consumption for kidneys.",
  "Get regular kidney function tests.",
  "Maintain a healthy weight always.",
  "Limit processed foods for kidneys.",
  "Control cholesterol levels for health.",
  "Avoid excessive NSAID use.",
  "Practice proper medication management.",
  "Get enough sleep for kidneys.",
  "Manage stress levels effectively.",
  "Limit phosphorus intake for kidneys.",
  "Avoid excessive protein intake.",
  "Choose whole grains for health.",
  "Consume healthy fats moderately.",
  "Control portion sizes for health.",
  "Limit caffeine intake for kidneys.",
  "Incorporate probiotics into diet.",
  "Monitor potassium levels regularly.",
  "Limit phosphorus-rich foods.",
  "Practice good dental hygiene habits.",
  "Use caution with herbal supplements.",
  "Get vaccinated to protect kidneys.",
  "Be mindful of fluid intake.",
  "Choose plant-based proteins often.",
  "Monitor kidney stone risk factors.",
  "Be cautious with high-protein diets.",
  "Keep blood pressure in check.",
  "Limit processed meats for kidneys.",
  "Control blood sugar levels carefully.",
  "Incorporate fruits daily for health.",
  "Avoid excessive red meat consumption.",
  "Monitor electrolyte levels regularly.",
  "Follow a heart-healthy diet.",
  "Avoid excessive alcohol consumption.",
  "Get regular physical activity.",
  "Manage stress levels effectively.",
  "Practice portion control consistently.",
  "Choose lean protein sources often.",
  "Control blood pressure effectively.",
  "Be cautious with over-the-counter meds.",
  "Limit sugar intake for kidney health.",
  "Incorporate leafy greens into diet.",
  "Avoid excessive caffeine consumption.",
  "Follow a low-sodium diet.",
  "Limit saturated fat intake.",
  "Be cautious with herbal supplements.",
  "Get regular check-ups for health.",
  "Monitor blood sugar levels closely.",
  "Avoid excessive salt in diet.",
  "Consume antioxidants regularly.",
  "Limit alcohol intake for health.",
  "Practice proper medication management.",
  "Follow a balanced diet consistently.",
  "Incorporate omega-3 fatty acids.",
  "Avoid tobacco products entirely.",
  "Practice relaxation techniques daily.",
  "Limit processed and packaged foods.",
  "Manage stress levels effectively.",
  "Monitor potassium levels regularly.",
  "Stay hydrated throughout the day.",
  "Choose healthy cooking methods.",
  "Practice portion control consistently.",
  "Get regular exercise for health.",
  "Be cautious with pain medications.",
  "Limit phosphorus intake for kidneys.",
  "Control blood pressure effectively.",
  "Avoid excessive sugar consumption.",
  "Incorporate nuts and seeds.",
  "Follow a kidney-friendly diet plan.",
  "Monitor fluid intake daily.",
  "Avoid high-sodium condiments.",
  "Get adequate rest for kidneys.",
  "Limit saturated fats for health.",
  "Choose whole grains over refined.",
  "Practice mindfulness in eating.",
  "Limit intake of processed foods.",
  "Consume dairy in moderation.",
  "Manage stress through hobbies.",
  "Incorporate fish into diet often.",
  "Limit alcohol intake for health.",
  "Monitor cholesterol levels regularly.",
  "Avoid excessive caffeine consumption.",
  "Control blood sugar levels effectively.",
  "Choose low-potassium fruits.",
  "Be cautious with high-protein diets.",
  "Use caution with salt substitutes.",
  "Practice gratitude for health.",
  "Avoid fad diets for kidneys.",
  "Incorporate legumes into diet.",
  "Limit intake of high-phosphorus foods.",
  "Seek support from loved ones.",
  "Get regular kidney check-ups.",
  "Choose water over sugary drinks."
];
