List<String> tips = [
         'Stay hydrated by drinking enough water daily.',
        'Control blood pressure through a healthy lifestyle.',
        'Monitor and manage diabetes to protect kidney function.',
        'Maintain a balanced diet with low sodium and phosphorus.',
        'Limit the intake of processed and high-sugar foods.',
        'Exercise regularly to support overall health.',
        'Quit smoking to reduce the risk of kidney disease.',
        'Limit alcohol consumption for kidney health.',
        'Avoid excessive use of over-the-counter painkillers.',
        'Manage stress through relaxation techniques.',
        'Control cholesterol levels through a heart-healthy diet.', 
        'Be mindful of salt intake to prevent fluid retention.',
        'Get regular check-ups to monitor kidney function.',
        'Maintain a healthy weight through diet and exercise.',
        'Limit caffeine intake for kidney stone prevention.',
        'Include kidney-friendly foods like berries and cabbage.',
        'Monitor protein intake for those with kidney issues.',
        'Limit phosphorus-rich foods for kidney patients.',
        'Protect kidneys from injury by wearing seat belts.',
        'Stay informed about medications and their impact on kidneys.',
];